"use client";
import Link from "next/link";
import {FormEvent,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
const morning=["09:00 AM","09:20 AM","09:40 AM","10:00 AM","10:20 AM","10:40 AM","11:00 AM"];
const evening=["05:00 PM","05:20 PM","05:40 PM","06:00 PM","06:20 PM","06:40 PM","07:00 PM"];
export default function AppointmentForm(){
 const router=useRouter(); const today=useMemo(()=>new Date().toISOString().split("T")[0],[]); const[date,setDate]=useState(today); const[time,setTime]=useState(""); const[sending,setSending]=useState(false); const[error,setError]=useState("");
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(!date||!time){setError("Appointment ke liye din aur samay chuniye.");return}const data=new FormData(e.currentTarget);if(data.get("website"))return;const ref=`SC-${Date.now().toString().slice(-6)}`;const booking={ref,name:String(data.get("name")||""),phone:String(data.get("phone")||""),doctor:String(data.get("doctor")||""),service:String(data.get("service")||""),date,time};setSending(true);sessionStorage.setItem("sampurna-clinic-booking",JSON.stringify(booking));setTimeout(()=>router.push(`/appointment/success?ref=${encodeURIComponent(ref)}`),650)}
 const slots=(items:string[])=>items.map(slot=><button type="button" key={slot} className={time===slot?"slot active":"slot"} onClick={()=>setTime(slot)} aria-pressed={time===slot}><span>○</span>{slot}</button>);
 return <form className="booking-form" onSubmit={submit}>
 <div className="booking-section"><div className="booking-heading"><span>1</span><div><h2>Doctor aur service choose karein</h2><p>Dr. Kanchan ke saath consultation request karein.</p></div></div><div className="field-grid"><label>Doctor<select name="doctor" required defaultValue=""><option value="" disabled>Doctor chuniye</option><option>Dr. Kanchan</option></select></label><label>Service<select name="service" required defaultValue=""><option value="" disabled>Service chuniye</option><option>Gynecology Consultation</option><option>Pregnancy & Maternity Care</option><option>Infertility Consultation</option><option>Menstrual & PCOS Care</option><option>Menopause Care</option><option>Not sure yet</option></select></label></div></div>
 <div className="booking-section"><div className="booking-heading"><span>2</span><div><h2>Preferred date choose karein</h2><p>Appointment clinic confirmation ke baad final hogi.</p></div></div><label className="date-field">Preferred Date<input name="date" type="date" min={today} value={date} onChange={e=>setDate(e.target.value)} required/></label></div>
 <div className="booking-section"><div className="booking-heading"><span>3</span><div><h2>Preferred time choose karein</h2><p>Selected time blue colour mein dikhega.</p></div></div><div className="slot-group"><h3>☀️ Subah</h3><div className="slot-grid">{slots(morning)}</div></div><div className="slot-group"><h3>🌇 Shaam</h3><div className="slot-grid">{slots(evening)}</div></div><input type="hidden" name="time" value={time}/></div>
 <div className="booking-section"><div className="booking-heading"><span>4</span><div><h2>Contact details bharein</h2><p>Clinic team confirmation ke liye is number ka use karegi.</p></div></div><div className="field-grid"><label>Patient Name<input name="name" autoComplete="name" required minLength={2} placeholder="Patient ka poora naam"/></label><label>Mobile Number<input name="phone" type="tel" inputMode="tel" autoComplete="tel" required pattern="[0-9 +()-]{8,18}" placeholder="+91 00000 00000"/></label><label>Email <small>(optional)</small><input name="email" type="email" autoComplete="email" placeholder="name@example.com"/></label><label>Age <small>(optional)</small><input name="age" inputMode="numeric" placeholder="Jaise: 28 years"/></label></div><label>Reason for visit <small>(sensitive medical details na likhein)</small><textarea name="message" rows={3} placeholder="Example: general consultation"/></label></div>
 <label className="check booking-consent"><input type="checkbox" required/> Appointment ke baare mein contact ki permission deti/deta hoon aur <Link href="/privacy-policy">privacy notice</Link> padha hai.</label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/>{error&&<p className="booking-error" role="alert">{error}</p>}
 <div className="booking-submit"><div><b>Selected:</b><span>{date||"Date choose karein"} • {time||"Time choose karein"}</span></div><button className="button big-button" type="submit" disabled={sending}>{sending?"Submit ho raha hai…":"Appointment Request Submit Karein →"}</button></div><p className="form-note">Yeh appointment request hai. Availability clinic confirmation ke baad final hogi.</p></form>
}
