"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";

export default function AppointmentForm() {
  const [state, setState] = useState<"idle"|"sending"|"sent">("idle");
  function submit(e:FormEvent<HTMLFormElement>) { e.preventDefault(); setState("sending"); setTimeout(()=>setState("sent"),700); }
  if(state === "sent") return <div className="form-success" role="status"><span>✓</span><h2>Request received</h2><p>Thank you. This demo form is ready to connect to the clinic’s secure enquiry service before launch.</p><button onClick={()=>setState("idle")}>Send another request</button></div>;
  return <form className="appointment-form" onSubmit={submit}><div className="field-grid"><label>Parent / Guardian Name<input name="name" autoComplete="name" required minLength={2}/></label><label>Mobile Number<input name="phone" type="tel" autoComplete="tel" required pattern="[0-9 +()-]{8,18}"/></label><label>Email <span>(optional)</span><input name="email" type="email" autoComplete="email"/></label><label>Baby Care Service<select name="service" defaultValue=""><option value="" disabled>Select one</option><option>Baby Health Check</option><option>Vaccination Guidance</option><option>Common Illness Care</option><option>Samajh nahi aa raha</option></select></label><label>Din Chuniye<input name="date" type="date" required/></label><label>Samay Chuniye<select name="time" defaultValue=""><option value="" disabled>Samay chuniye</option><option>Subah</option><option>Dopahar</option><option>Shaam</option></select></label></div><label>Bachche ke baare mein chhoti baat <span>(optional — do not include sensitive medical details)</span><textarea name="message" rows={4}/></label><label className="check"><input type="checkbox" required/> I consent to being contacted about this appointment request and have read the <Link href="/privacy-policy">privacy notice</Link>.</label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/><button className="button" type="submit" disabled={state === "sending"}>{state === "sending" ? "Sending…" : "Appointment Book Karein →"}</button><p className="form-note">Submitting a request does not confirm an appointment. The clinic will contact you to confirm availability.</p></form>;
}

