"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";

export default function AppointmentForm() {
  const [state, setState] = useState<"idle"|"sending"|"sent">("idle");
  function submit(e:FormEvent<HTMLFormElement>) { e.preventDefault(); setState("sending"); setTimeout(()=>setState("sent"),700); }
  if(state === "sent") return <div className="form-success" role="status"><span>✓</span><h2>Request received</h2><p>Thank you. This demo form is ready to connect to the clinic’s secure enquiry service before launch.</p><button onClick={()=>setState("idle")}>Send another request</button></div>;
  return <form className="appointment-form" onSubmit={submit}><div className="field-grid"><label>Full name<input name="name" autoComplete="name" required minLength={2}/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" required pattern="[0-9 +()-]{8,18}"/></label><label>Email <span>(optional)</span><input name="email" type="email" autoComplete="email"/></label><label>Consultation type<select name="service" defaultValue=""><option value="" disabled>Select one</option><option>General consultation</option><option>Preventive care</option><option>Follow-up care</option><option>Not sure yet</option></select></label><label>Preferred date<input name="date" type="date" required/></label><label>Preferred time<select name="time" defaultValue=""><option value="" disabled>Select a window</option><option>Morning</option><option>Afternoon</option><option>Evening</option></select></label></div><label>Brief note <span>(optional — do not include sensitive medical details)</span><textarea name="message" rows={4}/></label><label className="check"><input type="checkbox" required/> I consent to being contacted about this appointment request and have read the <Link href="/privacy-policy">privacy notice</Link>.</label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/><button className="button" type="submit" disabled={state === "sending"}>{state === "sending" ? "Sending…" : "Request appointment →"}</button><p className="form-note">Submitting a request does not confirm an appointment. The clinic will contact you to confirm availability.</p></form>;
}
