import Image from "next/image";
import Link from "next/link";
import {CTA,Footer,Header} from "../components";
import {clinic,services} from "../data";
export const metadata={title:`Women’s Health Services | ${clinic.name}`,description:"Explore women’s health, maternity, fertility and preventive consultations at Sampurna Clinic in Gyanpur, Bhadohi."};
const checks=["Careful discussion of symptoms and concerns","Review of relevant history and current medicines","Clinical assessment based on individual need","Clear explanation of possible next steps"];
export default function Services(){return <><Header/><main className="services-editorial">
<section className="services-hero"><Image src="/clinic-consultation-v2.png" alt="Representative doctor explaining a women’s health assessment" fill priority sizes="100vw"/><div className="services-hero-shade"/><div><p className="eyebrow">Sampurna Clinic • Clinical Services</p><h1>Women’s health check-ups with time to listen and explain.</h1><p>Private consultations for gynecology, maternity, fertility and preventive health concerns in Gyanpur, Bhadohi.</p><Link className="button" href="/appointment">Request an Appointment →</Link></div></section>
<section className="services-overview"><div><p className="eyebrow">What to expect</p><h2>A thoughtful check-up, shaped around the individual.</h2></div><div><p>Every patient’s symptoms, history and priorities are different. A consultation begins with listening and may include examination, investigation, guidance, treatment or referral depending on the doctor’s clinical assessment.</p><ul>{checks.map(item=><li key={item}>✓ {item}</li>)}</ul></div></section>
<section className="services-catalog"><header><div><p className="eyebrow">Consultation areas</p><h2>How we can help</h2></div><p>Select a service to understand its purpose, who may find it helpful and what to expect during the visit.</p></header><div className="services-catalog-grid">{services.map((s,i)=><Link href={`/services/${s.slug}`} key={s.slug}><small>{String(i+1).padStart(2,"0")}</small><span>{s.icon}</span><h3>{s.title}</h3><p>{s.short}</p><b>View Service Details <i>→</i></b></Link>)}</div></section>
<section className="services-feature"><div><Image src="/clinic-reception-v2.png" alt="Representative clinic reception and nursing support" fill sizes="(max-width:900px) 100vw,48vw"/></div><article><p className="eyebrow">Patient-first experience</p><h2>Professional support before, during and after the visit.</h2><p>The clinic journey is designed to be simple and respectful—from choosing a consultation to understanding the doctor’s advice.</p><div className="service-values"><span><b>Private</b>Personal health conversations are handled respectfully.</span><span><b>Prepared</b>Bring relevant reports, prescriptions and medicine details.</span><span><b>Clear</b>Questions and next steps should be explained understandably.</span></div><Link className="button" href="/appointment">Request an Appointment →</Link></article></section>
<section className="services-process"><header><p className="eyebrow">Our consultation process</p><h2>From request to follow-up</h2></header><ol><li><span>01</span><div><h3>Request an appointment</h3><p>Choose the relevant service, preferred date and time.</p></div></li><li><span>02</span><div><h3>Clinic confirmation</h3><p>The clinic team confirms availability using your contact number.</p></div></li><li><span>03</span><div><h3>Consultation and assessment</h3><p>Discuss symptoms, relevant history and health questions privately.</p></div></li><li><span>04</span><div><h3>Clinical next steps</h3><p>The doctor explains advice, tests, treatment or referral when appropriate.</p></div></li><li><span>05</span><div><h3>Follow-up</h3><p>Return or reconnect when follow-up is recommended by the doctor.</p></div></li></ol></section>
<section className="services-safety"><div><p className="eyebrow">Important</p><h2>Website information does not replace medical assessment.</h2></div><p>Service descriptions are general information. They cannot confirm a diagnosis or guarantee a treatment outcome. Do not use the website for emergencies; contact the nearest hospital or emergency service immediately.</p></section>
<CTA/></main><Footer/></>}

