import Image from "next/image";
import Link from "next/link";
import {Footer,Header} from "../components";
import {clinic} from "../data";
export const metadata={title:`Contact & Directions | ${clinic.name}`,description:"Find Sampurna Clinic in Gyanpur, Bhadohi, view directions and request an appointment."};
const mapUrl="https://www.google.com/maps?q=Sampurna+Clinic+Gyanpur+Dehat+Bhadohi&output=embed";
const directionsUrl="https://www.google.com/maps/search/?api=1&query=Sampurna+Clinic+Gyanpur+Dehat+Bhadohi";
export default function ContactPage(){return <><Header/><main className="contact-editorial">
<section className="contact-hero"><div className="contact-hero-copy"><p className="eyebrow">Contact Sampurna Clinic</p><h1>Plan your visit with confidence.</h1><p>Find the clinic, review the landmark and request an appointment before travelling.</p></div><div className="contact-hero-image"><Image src="/clinic-reception-v2.png" alt="Representative clinic reception and nursing support" fill priority sizes="(max-width:900px) 100vw,50vw"/></div></section>
<section className="contact-action-card"><div><p className="eyebrow">Appointment request</p><h2>Choose your preferred date and time online.</h2><p>The clinic team will confirm availability after a verified contact number is connected.</p></div><div><Link className="button" href="/appointment">Book an Appointment →</Link><Link href="/services">Explore Services</Link></div></section>
<section className="contact-find"><header><p className="eyebrow">Find us here</p><h2>Easy directions to Sampurna Clinic</h2><p>Use the address, nearby landmark or Google Maps button to plan your journey.</p></header><div className="contact-info-grid"><article><span>☎</span><div><small>Phone & WhatsApp</small><strong>{clinic.phoneDisplay}</strong><p>Direct calling will be enabled after verification.</p></div></article><article><span>✉</span><div><small>Email</small><strong>{clinic.email}</strong><p>Verified clinic email will be added here.</p></div></article><article><span>⌖</span><div><small>Clinic address</small><strong>{clinic.address}</strong><p>Landmark: beside the Primary School.</p></div></article></div>
<div className="contact-map-shell"><iframe title="Map showing Sampurna Clinic search location in Gyanpur, Bhadohi" src={mapUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><div className="contact-map-overlay"><p className="eyebrow">Navigation</p><h3>Open turn-by-turn directions</h3><p>Google Maps will search for Sampurna Clinic near Gyanpur Dehat, Bhadohi.</p><a className="button" href={directionsUrl} target="_blank" rel="noopener noreferrer">Open in Google Maps →</a></div></div></section>
<section className="contact-journey"><div><p className="eyebrow">Before you leave</p><h2>A smoother clinic visit in four steps.</h2></div><ol><li><span>01</span><div><b>Request</b><p>Choose a service, date and preferred time online.</p></div></li><li><span>02</span><div><b>Confirm</b><p>Wait for the clinic to confirm availability.</p></div></li><li><span>03</span><div><b>Prepare</b><p>Bring relevant reports, prescriptions and medicine details.</p></div></li><li><span>04</span><div><b>Navigate</b><p>Use the Primary School landmark or open Google Maps.</p></div></li></ol></section>
<section className="contact-hours"><div><Image src="/sampurna-clinic-logo.png" alt="Sampurna Clinic logo" width={150} height={150}/><div><p className="eyebrow">Clinic information</p><h2>Sampurna Clinic</h2><p>Women’s Health, Maternity & Infertility Care</p></div></div><dl><div><dt>Doctor</dt><dd>Dr. Kanchan</dd></div><div><dt>Qualification</dt><dd>PGDMHC, IMS-B.H.U.</dd></div><div><dt>Consultation hours</dt><dd>{clinic.hours}</dd></div><div><dt>Location</dt><dd>Gyanpur, Bhadohi</dd></div></dl></section>
<section className="contact-safety"><b>Need urgent medical help?</b><p>Do not use the website or appointment form for emergencies. Contact the nearest hospital or local emergency service immediately.</p></section>
</main><Footer/></>}
