import Image from "next/image";
import Link from "next/link";
import {CTA,Footer,Header} from "../components";
import {clinic,doctors} from "../data";
const doctor=doctors[0];
export const metadata={title:`Pelvic & Bladder Health Guide | ${clinic.name}`,description:"An educational guide to pelvic floor and bladder symptoms, consultation and next steps from Sampurna Clinic."};
const concerns=[{n:"01",title:"Urine leakage",text:"Leakage during coughing, sneezing, exercise or before reaching a toilet should not be ignored. Different patterns can have different causes."},{n:"02",title:"Pelvic pressure or heaviness",text:"A feeling of pressure, heaviness or a vaginal bulge deserves professional assessment, especially when it affects daily activity."},{n:"03",title:"Repeated urinary symptoms",text:"Burning, urgency, frequency or repeated urinary infections may need clinical review and appropriate testing."},{n:"04",title:"Persistent pelvic discomfort",text:"Ongoing bladder or pelvic pain can have several possible causes. A consultation helps determine suitable next steps."}];
const faqs=[{q:"When should I request a consultation?",a:"Request an appointment when symptoms persist, return repeatedly, affect daily life or cause concern. Sudden or severe symptoms need urgent medical attention."},{q:"Will every patient need tests?",a:"No. Tests depend on symptoms, history and clinical assessment. The doctor should explain why any investigation is suggested."},{q:"Does every concern require surgery?",a:"No. Management may involve observation, lifestyle guidance, medicines, physiotherapy, referral or procedures depending on the confirmed diagnosis and available services."},{q:"What should I bring?",a:"Bring relevant prescriptions, reports, urine-test results when available and a list of current medicines and allergies."}];
export default function BlogPage(){return <><Header/><main className="blog-feature">
<section className="blog-feature-hero"><Image src="/clinic-consultation-v2.png" alt="Representative private gynecology consultation" fill priority sizes="100vw"/><div/><article><span>Women’s Health Guide</span><h1>Pelvic floor and bladder symptoms: when to seek help.</h1><p>Educational information from Sampurna Clinic • Reviewed clinic details pending</p></article></section>
<section className="blog-meta"><div><Image src="/sampurna-clinic-logo.png" alt="Sampurna Clinic logo" width={70} height={70}/><p><b>{doctor.name}</b><span>{doctor.qualification} • {doctor.role}</span></p></div><p>Educational article • Not a diagnosis</p></section>
<article className="blog-article"><header><p className="eyebrow">Understanding the concern</p><h2>Symptoms can affect comfort, confidence and daily life.</h2></header><div className="blog-intro-grid"><aside>Many women delay discussing urine leakage, pelvic pressure or discomfort because they feel embarrassed. These concerns are common reasons to seek professional guidance and deserve privacy and respect.</aside><div><p>Pelvic floor and bladder symptoms can have different causes. A proper consultation reviews the pattern of symptoms, relevant medical and pregnancy history, medicines and their effect on everyday activities.</p><p>This guide explains common signs, what a consultation may include and when urgent medical attention may be necessary. It does not confirm whether a particular condition or treatment applies to you.</p></div></div>
<section className="blog-concerns"><h2>Common reasons to consult a gynecologist</h2><div>{concerns.map(item=><article key={item.n}><span>{item.n}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
<figure className="blog-wide-image"><Image src="/doctor-care-hero-v2.png" alt="Representative mother, baby and women’s health collage" fill sizes="100vw"/><figcaption>Women’s health concerns can be discussed privately at every life stage.</figcaption></figure>
<section className="blog-assessment"><div><p className="eyebrow">During the consultation</p><h2>Assessment before assumptions.</h2><p>The doctor may ask about when symptoms began, what makes them better or worse, pregnancy and delivery history, current medicines, previous treatment and any impact on sleep, work or activity.</p></div><ol><li><b>Listen</b><span>Discuss symptoms and concerns privately.</span></li><li><b>Review</b><span>Consider relevant history, reports and medicines.</span></li><li><b>Assess</b><span>Examination or investigations only when clinically appropriate.</span></li><li><b>Plan</b><span>Explain guidance, treatment, follow-up or referral.</span></li></ol></section>
<section className="blog-options"><div><Image src="/clinic-reception-v2.png" alt="Representative clinic reception and nursing support" fill sizes="(max-width:900px) 100vw,45vw"/></div><article><p className="eyebrow">Possible next steps</p><h2>Care depends on the confirmed cause.</h2><p>Depending on assessment and services available at the clinic, next steps may include lifestyle guidance, pelvic-floor support, medicines, investigations, follow-up or referral to an appropriate specialist.</p><div className="blog-note"><b>Important:</b> This website does not claim that Sampurna Clinic provides every urogynecology test, procedure or surgery shown on other websites. Confirm available services directly with the clinic.</div><Link className="button" href="/appointment">Request a Consultation →</Link></article></section>
<section className="blog-faq"><header><p className="eyebrow">Frequently asked questions</p><h2>Helpful answers before your visit</h2></header><div>{faqs.map((item,i)=><details key={item.q} open={i===0}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div></section>
<section className="blog-urgent"><h2>When to seek urgent help</h2><p>Seek urgent medical care for severe or sudden pelvic pain, heavy bleeding, inability to pass urine, fever with worsening urinary symptoms, fainting or any symptom that feels life-threatening. Do not wait for an online appointment response.</p></section>
</article><CTA/></main><Footer/></>}
