import Image from "next/image";
import Link from "next/link";
import {Footer,Header} from "../components";
import {clinic,doctors} from "../data";
const doctor=doctors[0];
export const metadata={title:"About Sampurna Clinic & Dr. Kanchan",description:"Learn about Sampurna Clinic, Dr. Kanchan and the clinic’s approach to private women’s healthcare in Gyanpur, Bhadohi."};
export default function AboutPage(){return <><Header/><main className="about-editorial">
<section className="about-banner"><Image src="/clinic-consultation-v2.png" alt="Representative private women’s health consultation" fill priority sizes="100vw"/><div className="about-banner-shade"/><div className="about-banner-copy"><p>Sampurna Clinic • Gyanpur, Bhadohi</p><h1>Women’s healthcare built around listening, privacy and clarity.</h1><Link className="button" href="/appointment">Request an Appointment</Link></div></section>
<section className="about-intro-card"><Image src="/sampurna-clinic-logo.png" alt="Sampurna Clinic logo" width={150} height={150}/><div><p className="eyebrow">Meet the doctor</p><h2>{doctor.name}</h2><strong>{doctor.qualification}</strong><p>{doctor.role}</p><Link href={`/doctors/${doctor.slug}`}>View complete profile →</Link></div></section>
<section className="about-opening"><div><p className="eyebrow">About</p><h2>Sampurna Clinic</h2></div><div><p>Sampurna Clinic provides a private and respectful setting for women to discuss gynecology, maternity and fertility concerns. Each visit begins with careful listening and an individual clinical assessment.</p><p>The clinic is located in Gyanpur Dehat, beside the Primary School, Gyanpur, Bhadohi. Verified consultation hours and direct contact details will be published after confirmation.</p></div></section>
<section className="about-story"><header><span>✦</span><div><p className="eyebrow">About the doctor</p><h2>Dr. Kanchan</h2></div></header><div className="about-story-lead"><p>The supplied clinic letterhead identifies Dr. Kanchan as PGDMHC, IMS-B.H.U., providing women’s health, maternity and infertility care at Sampurna Clinic. Experience, registration and consultation hours will be added only after verification.</p><Image src="/clinic-hero-v2.png" alt="Representative women’s healthcare professional" width={520} height={340}/></div>
<div className="about-timeline"><article><span>01</span><div><p className="eyebrow">Private consultations</p><h3>Care that begins with listening</h3><p>Personal concerns deserve time and privacy. The consultation is designed to help patients explain symptoms comfortably and understand the next step.</p></div><Image src="/clinic-consultation-v2.png" alt="Representative doctor consultation" width={440} height={280}/></article><article><span>02</span><div><p className="eyebrow">Women’s health</p><h3>Menstrual and hormonal concerns</h3><p>Patients may request guidance for irregular cycles, heavy bleeding, painful periods, PCOS-related symptoms or other changes that require clinical assessment.</p></div><div className="about-topic-visual">Women’s Health<br/><small>Individual assessment • Clear guidance</small></div></article><article><span>03</span><div><p className="eyebrow">Maternity care</p><h3>Support during pregnancy</h3><p>Pregnancy consultations may include stage-appropriate guidance, follow-up planning and discussion of concerns. Recommendations depend on individual clinical needs.</p></div><Image src="/clinic-reception-v2.png" alt="Representative clinic reception and nursing team" width={440} height={280}/></article><article><span>04</span><div><p className="eyebrow">Fertility guidance</p><h3>A respectful first conversation</h3><p>Fertility concerns can be discussed privately. The doctor may recommend evaluation, counselling or referral after reviewing the patient’s history and clinical needs.</p></div><div className="about-topic-visual alternate">Fertility Consultation<br/><small>Questions • Evaluation • Next steps</small></div></article></div></section>
<section className="about-contact-band"><div><p className="eyebrow">Visit Sampurna Clinic</p><h2>Plan your consultation.</h2><p>{clinic.address}</p></div><div><p><b>Phone:</b> {clinic.phoneDisplay}</p><p><b>Hours:</b> {clinic.hours}</p><Link className="button" href="/appointment">Book Appointment</Link><a href="https://www.google.com/maps/search/?api=1&query=Sampurna+Clinic+Gyanpur+Dehat+Bhadohi" target="_blank" rel="noopener noreferrer">Open in Google Maps →</a></div></section>
</main><Footer/></>}
