import Image from "next/image";
import Link from "next/link";
import {clinic} from "./data";
export function Logo(){return <Link className="brand gyn-brand sampurna-brand" href="/" aria-label={`${clinic.name} home`}><Image src="/sampurna-clinic-logo.png" alt="Sampurna Clinic Gyanpur Bhadohi logo" width={58} height={58}/><span><strong>{clinic.nameHindi}</strong><small>{clinic.name} · Gyanpur, Bhadohi</small></span></Link>}
const links=<><Link href="/">Home</Link><Link href="/about">About</Link><Link href="/doctors">Doctor</Link><Link href="/services">Services</Link><Link href="/gallery">Clinic</Link><Link href="/faq">FAQs</Link><Link href="/contact">Contact</Link></>;
export function Header(){return <><div className="top-note gyn-top">स्त्री, प्रसूति व बांझपन रोग परामर्श • Women’s health with privacy and respect</div><header className="site-header gyn-header"><Logo/><nav aria-label="Primary navigation">{links}</nav><details className="mobile-nav"><summary aria-label="Open menu">☰</summary><div>{links}</div></details><Link className="button button-small" href="/appointment">Book Appointment</Link></header><div className="floating-contacts" aria-label="Quick contact"><Link className="float-contact whatsapp-float" href="/contact" aria-label="View clinic contact details" title="Contact Clinic"><span className="wa-mark">✉</span><b>Contact</b></Link><Link className="float-contact phone-float" href="/appointment" aria-label="Book appointment" title="Book Appointment"><span>📅</span><b>Book</b></Link></div></>}
export function Footer(){return <footer className="gyn-footer"><div className="footer-main"><div><Logo/><p>Gyanpur aur Bhadohi ki mahilaon ke liye private, respectful aur clearly explained care.</p></div><div><h3>Explore</h3><Link href="/about">About the Clinic</Link><Link href="/doctors">Dr. Kanchan</Link><Link href="/services">Services</Link><Link href="/faq">FAQs</Link></div><div><h3>Visit</h3><p>{clinic.address}</p><p>{clinic.hours}</p></div><div><h3>Contact</h3><p>{clinic.phoneDisplay}</p><p>{clinic.email}</p><Link className="footer-book" href="/appointment">Book Appointment</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {clinic.name}, Gyanpur</span><span><Link href="/privacy-policy">Privacy</Link> · <Link href="/terms">Terms</Link></span></div></footer>}
export function PageHero({eyebrow,title,intro}:{eyebrow:string,title:string,intro:string}){return <section className="page-hero gyn-page-hero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p></section>}
export function CTA(){return <section className="gyn-cta"><div><p className="eyebrow">Private consultation request</p><h2>Apni health concern ko bina jhijhak discuss karein.</h2><p>Preferred date aur time choose karein. Appointment clinic confirmation ke baad final hogi.</p></div><div className="gyn-cta-card"><span>01</span><h3>Sampurna Clinic, Gyanpur</h3><Link className="button" href="/appointment">Book Appointment →</Link><Link href="/contact">Address & clinic details</Link></div></section>}
