import Link from "next/link";
import { clinic } from "./data";

export function Logo(){return <Link className="brand" href="/" aria-label={`${clinic.name} home`}><span className="brand-mark">❤</span><span><strong>Nanhe Kadam</strong><small>Child Clinic</small></span></Link>}
const links=<><Link href="/">Home</Link><Link href="/about">Clinic / Hamari Clinic</Link><Link href="/doctors">Doctors / Doctor</Link><Link href="/services">Services / Baby Care</Link><Link href="/gallery">Photos / Tasveerein</Link><Link href="/faq">Help / Sawaal</Link><Link href="/contact">Contact / Sampark</Link></>;
export function Header(){return <><div className="top-note">Simple child care for village families • Gaon ke bachchon ke liye pyaar bhari care</div><header className="site-header"><Logo/><nav aria-label="Primary navigation">{links}</nav><details className="mobile-nav"><summary aria-label="Open menu">☰</summary><div>{links}</div></details><Link className="button button-small" href="/appointment">Book Appointment / Booking</Link></header><div className="floating-contacts" aria-label="Quick contact"><a className="float-contact whatsapp-float" href="https://wa.me/910000000000?text=Namaste%2C%20mujhe%20baby%20appointment%20book%20karna%20hai" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp par clinic se baat karein" title="WhatsApp"><span className="wa-mark">☎</span><b>WhatsApp</b></a><a className="float-contact phone-float" href={`tel:${clinic.phone}`} aria-label="Clinic ko phone karein" title="Call Clinic"><span>☎</span><b>Call</b></a></div></>}
export function Footer(){return <footer><div className="footer-main"><div><Logo/><p>Bachchon ki sehat ke liye saral, saaf aur bharosemand clinic experience.</p></div><div><h3>Quick Links</h3><Link href="/about">Hamari Clinic</Link><Link href="/services">Services / Baby Care</Link><Link href="/faq">Sawal-Jawab</Link><Link href="/contact">Sampark</Link></div><div><h3>Clinic Address</h3><p>{clinic.address}</p><p>{clinic.hours}</p></div><div><h3>Phone</h3><a href={`tel:${clinic.phone}`}>{clinic.phoneDisplay}</a><Link className="footer-book" href="/appointment">Book Appointment / Appointment Book Karein</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {clinic.name}</span><span><Link href="/privacy-policy">Privacy</Link> · <Link href="/terms">Terms</Link></span></div></footer>}
export function PageHero({eyebrow,title,intro}:{eyebrow:string,title:string,intro:string}){return <section className="page-hero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p></section>}
export function CTA(){return <section className="cta care-cta"><div className="cta-copy"><span className="cta-badge">👶 Simple Baby Appointment</span><h2>Meeting a child doctor is now simple. / Bachche ke liye doctor se milna ab bilkul aasaan.</h2><p>Choose a doctor, date and time. / Doctor, din aur samay chuniye; clinic team phone par confirm karegi.</p><div className="cta-trust"><span>✓ 2 minute booking</span><span>✓ Aasaan Hindi-English</span><span>✓ Phone confirmation</span></div></div><div className="cta-action-card"><span className="cta-calendar">📅</span><h3>Aaj hi request bhejein</h3><p>Koi online payment nahi. Pehle clinic confirmation milega.</p><Link className="button cta-primary" href="/appointment">Book Appointment / Appointment Book Karein <span>→</span></Link><a className="cta-phone" href={`tel:${clinic.phone}`}>☎ Or call / Ya phone karein: {clinic.phoneDisplay}</a></div></section>}




