import Image from "next/image";
import Link from "next/link";
import { CTA,Footer,Header } from "./components";
import { doctors,faqs,services } from "./data";

export default function Home(){return <><Header/><main>
<section className="baby-hero"><div className="baby-copy"><span className="friendly-pill">👶 Baby & Child Care • Gaon ke paas</span><h1>Nanhe bachchon ki <em>sehat</em>, hamari zimmedari.</h1><p>Baby ki tabiyat, teekakaran, growth ya khaane se jude sawal? Doctor se milna ab simple hai. Phone karein ya 2 minute mein appointment book karein.</p><div className="hero-actions"><Link className="button big-button" href="/appointment">📅 Appointment Book Karein</Link><a className="call-button" href="tel:+910000000000">☎ Phone Karein</a></div><div className="mini-trust"><span>✓ Saaf clinic</span><span>✓ Aasaan bhaasha</span><span>✓ Bachchon ke liye friendly</span></div></div><div className="baby-photo"><Image src="/baby-doctor.png" alt="Child doctor talking kindly with a mother and baby in a village clinic" fill priority sizes="(max-width: 800px) 100vw, 48vw"/><div className="photo-badge"><b>Doctor se seedhi baat</b><small>Har sawal pooch sakte hain</small></div></div></section>
<section className="easy-actions" aria-label="Quick clinic actions"><Link href="/appointment"><b>📅</b><span><strong>Appointment</strong><small>Din aur samay chuniye</small></span><i>→</i></Link><Link href="/contact"><b>🕐</b><span><strong>Clinic Time</strong><small>Timing aur pata dekhein</small></span><i>→</i></Link><a href="tel:+910000000000"><b>☎</b><span><strong>Phone Karein</strong><small>Clinic team se baat karein</small></span><i>→</i></a></section>
<section className="simple-section intro-care"><div><p className="section-label">Hamari Clinic</p><h2>Chhoti clinic. Badi care.</h2><p>Village families ke liye banayi gayi simple child-care website. Bade letters, saaf jankari aur har jagah seedha appointment button.</p><div className="care-points"><span>🧒 Bachche ko pyaar se samjhana</span><span>💬 Maa-baap ke sawalon ka jawab</span><span>📋 Agla kadam saaf batana</span></div><Link className="button" href="/about">Clinic ke baare mein →</Link></div><div className="clinic-photo"><Image src="/village-clinic.png" alt="Clean blue and white child clinic in an Indian village" fill sizes="(max-width: 800px) 100vw, 46vw"/></div></section>
<section className="blue-band simple-section"><div className="section-title"><p className="section-label">Baby Care Services</p><h2>Bachche ko kis baat mein madad chahiye?</h2><p>Service chuniye aur simple shabdon mein janiye ki doctor se milte waqt kya hoga.</p></div><div className="baby-services">{services.map(s=><Link href={`/services/${s.slug}`} key={s.slug}><b>{s.icon}</b><h3>{s.title}</h3><p>{s.short}</p><span>Jankari dekhein →</span></Link>)}</div></section>
<section className="simple-section steps"><div className="section-title"><p className="section-label">Bahut Aasaan</p><h2>3 step mein appointment</h2></div><ol><li><b>1</b><div><h3>Button dabaiye</h3><p>“Appointment Book Karein” par click karein.</p></div></li><li><b>2</b><div><h3>Naam aur phone likhein</h3><p>Bachche ke liye din aur samay chuniye.</p></div></li><li><b>3</b><div><h3>Clinic ka phone aayega</h3><p>Team aapka appointment confirm karegi.</p></div></li></ol><Link className="button big-button" href="/appointment">Abhi Book Karein →</Link></section>
<section className="reception-section simple-section"><div className="section-title"><p className="section-label">Clinic Reception</p><h2>Reception se doctor cabin tak, sab simple.</h2><p>Nurse se baat karein, apna number batayein aur aaram se baithkar turn ka wait karein.</p></div><div className="reception-photo"><Image src="/clinic-reception.png" alt="Village child clinic reception with nurse helping a mother and baby" fill sizes="100vw"/></div><div className="reception-steps"><span><b>1</b> Reception par naam batayein</span><span><b>2</b> Nurse basic details legi</span><span><b>3</b> Doctor cabin mein consultation</span></div></section>
<section className="home-doctors simple-section"><div className="section-title"><p className="section-label">Hamare Doctors</p><h2>3 doctor profiles, ek click mein.</h2><p>Doctor ki verified details aur rating asli information milne ke baad dikhengi.</p></div><div className="doctor-grid">{doctors.map(d=><article className="doctor-card" key={d.slug}><div className="doctor-avatar" style={{background:d.color}}>{d.initials}</div><div className="doctor-card-body"><span>Details pending</span><h3>{d.name}</h3><p>{d.role}</p><div className="rating-pending">☆ Verified rating pending</div><Link href={`/doctors/${d.slug}`}>Doctor Profile →</Link></div></article>)}</div><div className="center-action"><Link className="button" href="/doctors">Sabhi Doctors Dekhein</Link></div></section>
<section className="review-section simple-section"><div><p className="section-label">Patient Reviews</p><h2>Gaon ke parivaar kya kehte hain?</h2><p>Sirf consent ke saath mile asli reviews publish honge. Abhi review section ready hai, lekin koi fake patient quote ya rating nahi dikhayi gayi.</p><Link className="button" href="/testimonials">Reviews Page Dekhein</Link></div><div className="review-empty"><div className="stars">☆☆☆☆☆</div><h3>Verified reviews ka intezar</h3><p>Client ke Google Business Profile ya written consent wale reviews milte hi yahan doctor-wise rating show hogi.</p></div></section>
<section className="faq-preview simple-section"><div><p className="section-label">Sawal-Jawab</p><h2>Koi bhi sawal chhota nahi hota.</h2></div><div>{faqs.slice(0,4).map((f,i)=><details key={f.q} open={i===0}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div></section>
<CTA/></main><Footer/><div className="mobile-sticky"><a href="tel:+910000000000">☎ Call</a><Link href="/appointment">📅 Book</Link></div></>}


