import Link from "next/link";
import { CTA, Footer, Header } from "./components";
import { faqs, services } from "./data";
export default function Home() { return <><Header/><main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">Thoughtful care, close to home</p><h1>Healthcare that listens <em>before it treats.</em></h1><p className="hero-lede">A calm, modern clinic experience built around clear conversations, considered consultations and care that respects your time.</p><div className="hero-actions"><Link className="button" href="/appointment">Book a consultation <span>→</span></Link><a className="text-link" href="tel:+910000000000">Call the clinic <span>↗</span></a></div><div className="hero-note"><span>●</span> Appointments available by prior booking</div></div><div className="hero-visual" aria-label="Abstract representation of a caring clinician"><div className="arch arch-one"/><div className="arch arch-two"/><div className="visual-card"><span className="visual-icon">✦</span><p>Care that feels personal</p><small>Clear guidance at every step</small></div><div className="portrait-shape"><div className="portrait-head"/><div className="portrait-body"/></div></div></section>
  <section className="trust-strip" aria-label="Clinic information"><div><span>01</span><strong>By appointment</strong><small>Planned, unhurried visits</small></div><div><span>02</span><strong>Patient-first</strong><small>Questions are always welcome</small></div><div><span>03</span><strong>Easy to reach</strong><small>Call or book online</small></div></section>
  <section className="story section"><div className="story-art"><span>Care begins<br/>with context.</span></div><div><p className="eyebrow">Our approach</p><h2>A clinic experience designed around <em>how care should feel.</em></h2><p>Good healthcare starts with being heard. Every consultation is an opportunity to understand your concern, explain the options clearly and agree on a sensible next step.</p><p>We keep the experience straightforward—from requesting an appointment to planning a follow-up—so your attention can stay where it matters.</p><Link className="arrow-link" href="/about">Discover our care philosophy →</Link></div></section>
  <section className="services-section section"><div className="section-head"><div><p className="eyebrow">How we can help</p><h2>Care for the questions that bring you in.</h2></div><Link className="text-link" href="/services">View all services →</Link></div><div className="service-grid">{services.map(s=><article className="service-card" key={s.slug}><span>{s.icon}</span><h3>{s.title}</h3><p>{s.short}</p><Link aria-label={`Learn more about ${s.title}`} href={`/services/${s.slug}`}>Explore service ↗</Link></article>)}</div></section>
  <section className="journey section"><div><p className="eyebrow">A clearer care journey</p><h2>Simple steps. No unnecessary uncertainty.</h2></div><ol><li><span>1</span><div><h3>Request</h3><p>Tell us how to reach you and your preferred time.</p></div></li><li><span>2</span><div><h3>Confirm</h3><p>The clinic confirms availability and visit details.</p></div></li><li><span>3</span><div><h3>Consult</h3><p>Discuss your concern and ask the questions that matter.</p></div></li><li><span>4</span><div><h3>Next step</h3><p>Leave with clear guidance for treatment or follow-up.</p></div></li></ol></section>
  <section className="faq-preview section"><div><p className="eyebrow">Good to know</p><h2>Questions before your visit.</h2><Link className="arrow-link" href="/faq">See all frequently asked questions →</Link></div><div>{faqs.slice(0,3).map((f,i)=><details key={f.q} open={i===0}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div></section>
  <CTA/>
  </main><Footer/></>; }
