import Image from "next/image";
import Link from "next/link";
import {CTA,Footer,Header} from "./components";
import {doctors,faqs,services} from "./data";
export default function Home(){const doctor=doctors[0];return <><Header/><main className="gyn-home">
<section className="gyn-hero"><Image src="/gynecologist-hero.png" alt="Representative women’s health consultation visual" fill priority sizes="100vw"/><div className="gyn-hero-overlay"/><div className="gyn-hero-copy"><p className="eyebrow">Sampurna Clinic • Gyanpur, Bhadohi</p><h1>Mahilaon ki sehat ke liye <em>samvedansheel aur sampoorna care.</em></h1><p>Dr. Kanchan ke saath women’s health, maternity aur infertility concerns ke liye private consultation.</p><div><Link className="button" href="/appointment">Appointment Book Karein →</Link><Link href="/contact">⌖ Gyanpur, Bhadohi</Link></div></div><div className="hero-corner">सम्पूर्ण क्लिनिक<br/><strong>Women’s Health Care</strong></div></section>
<section className="gyn-quick"><Link href="/appointment"><span>01</span><div><b>Book Appointment</b><small>Date aur time choose karein</small></div><i>→</i></Link><Link href="/doctors/dr-kanchan"><span>02</span><div><b>Doctor Profile</b><small>Dr. Kanchan</small></div><i>→</i></Link><Link href="/contact"><span>03</span><div><b>Clinic Information</b><small>Gyanpur, Bhadohi</small></div><i>→</i></Link></section>
<section className="gyn-section gyn-services"><div className="gyn-section-head"><div><p className="eyebrow">How we can help</p><h2>Women’s health services—simple language, respectful care.</h2></div><Link href="/services">View All Services →</Link></div><div className="gyn-service-grid">{services.slice(0,3).map((s,i)=><Link className={i===1?"featured":""} href={`/services/${s.slug}`} key={s.slug}><span>{s.icon}</span><small>0{i+1}</small><h3>{s.title}</h3><p>{s.short}</p><b>Learn More →</b></Link>)}</div></section>
<section className="gyn-doctor-section"><div className="gyn-doctor-image clinic-logo-panel"><Image src="/sampurna-clinic-logo.png" alt="Sampurna Clinic Gyanpur Bhadohi logo" fill sizes="(max-width:900px) 100vw, 45vw"/></div><div><p className="eyebrow">Meet the doctor</p><h2>Dr. Kanchan at Sampurna Clinic.</h2><p>Uploaded clinic details identify Dr. Kanchan for women’s health, maternity and infertility care. Registration number, experience and timings will be added after verification.</p><div className="doctor-fact-list"><span><b>Qualification</b>{doctor.qualification}</span><span><b>Speciality</b>{doctor.role}</span><span><b>Location</b>Gyanpur, Bhadohi</span></div><Link className="button" href={`/doctors/${doctor.slug}`}>View Doctor Profile →</Link></div></section>
<section className="gyn-dark"><div><p className="eyebrow">Care pathways</p><h2>Care for different stages of women’s health.</h2><p>Har consultation aapki concern aur relevant history se shuru hoti hai. Advice, examination, investigations ya referral individual doctor assessment par depend karega.</p><Link href="/services">Explore Services →</Link></div><div className="pathway-grid">{services.map((s,i)=><Link href={`/services/${s.slug}`} key={s.slug}><span>{String(i+1).padStart(2,"0")}</span><b>{s.title}</b></Link>)}</div></section>
<section className="gyn-process gyn-section"><div className="gyn-section-head"><div><p className="eyebrow">Your visit</p><h2>Appointment se consultation tak—simple process.</h2></div></div><ol><li><span>01</span><h3>Request</h3><p>Service, date aur preferred time choose karein.</p></li><li><span>02</span><h3>Confirm</h3><p>Clinic team availability confirm karegi.</p></li><li><span>03</span><h3>Consult</h3><p>Apni concern private setting mein discuss karein.</p></li><li><span>04</span><h3>Next Step</h3><p>Doctor assessment ke baad next step samjhayengi.</p></li></ol></section>
<section className="gyn-faq gyn-section"><div><p className="eyebrow">Frequently asked</p><h2>Visit se pehle zaroori answers.</h2><p>Clear information se clinic visit easy aur comfortable hoti hai.</p><Link href="/faq">View All FAQs →</Link></div><div>{faqs.slice(0,4).map((f,i)=><details key={f.q} open={i===0}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div></section>
<CTA/></main><Footer/></>}
