import {notFound} from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import {CTA,Footer,Header,PageHero} from "../components";
import {clinic,doctors,faqs} from "../data";
const doctor=doctors[0];
const pages:Record<string,{eyebrow:string,title:string,intro:string,body:React.ReactNode}>={
about:{eyebrow:"About Sampurna Clinic",title:"Respectful women’s healthcare in Gyanpur.",intro:"A private consultation experience designed to help patients feel heard, informed and comfortable.",body:<div className="prose-grid"><div><h2>Care begins with listening.</h2><p>Sampurna Clinic focuses on listening carefully, explaining concerns clearly and planning appropriate next steps.</p><Link className="button" href="/appointment">Book Appointment</Link></div><div className="principles"><article><span>01</span><h3>Private</h3><p>A respectful setting for personal health conversations.</p></article><article><span>02</span><h3>Clear</h3><p>Clear information in easy-to-understand English.</p></article><article><span>03</span><h3>Individual</h3><p>Next steps depend on the doctor’s individual clinical assessment.</p></article></div></div>},
doctors:{eyebrow:"Doctor profile",title:"Meet Dr. Kanchan.",intro:"Women’s health, maternity and infertility care at Sampurna Clinic, Gyanpur.",body:<div className="doctor-showcase"><div className="doctor-photo clinic-logo-panel"><Image src="/sampurna-clinic-logo.png" alt="Sampurna Clinic logo" fill sizes="(max-width:800px) 100vw,45vw"/></div><div><span>Sampurna Clinic • Gyanpur</span><h2>{doctor.name}</h2><p>{doctor.role}</p><p><b>Qualification:</b> {doctor.qualification}</p><p>Approved doctor photograph, registration, experience and consultation timings will be added after verification.</p><Link className="button" href={`/doctors/${doctor.slug}`}>View Doctor Profile</Link></div></div>},
gallery:{eyebrow:"Clinic",title:"Sampurna Clinic, Gyanpur.",intro:"Clinic exterior, reception and consultation-room photographs can be added after they are shared.",body:<div className="real-gallery"><div><Image src="/clinic-reception-v2.png" alt="Sampurna Clinic letterhead with Dr. Kanchan details" fill sizes="100vw"/></div><div><Image src="/clinic-consultation-v2.png" alt="Representative private consultation room" fill sizes="100vw"/></div></div>},
testimonials:{eyebrow:"Patient experiences",title:"Real feedback only.",intro:"Ratings and testimonials will be published only from a verifiable source and with appropriate consent.",body:<div className="empty-state"><h2>Verified reviews pending.</h2><p>No fabricated ratings, patient counts or quotations are used.</p></div>},
faq:{eyebrow:"Frequently asked questions",title:"Helpful information before your visit.",intro:"Clear answers about appointments, location, the doctor profile and clinic visits.",body:<div className="faq-list">{faqs.map((f,i)=><details key={f.q} open={i===0}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div>},
blog:{eyebrow:"Women’s health journal",title:"Reviewed health information.",intro:"Educational articles identified author, review date and reliable sources ke saath add honge.",body:<div className="empty-state"><h2>Clinical articles awaiting review.</h2><p>Website information consultation, diagnosis ya treatment ko replace nahi karti.</p></div>},
contact:{eyebrow:"Contact Sampurna Clinic",title:"Visit Sampurna Clinic in Gyanpur.",intro:"Call and WhatsApp buttons will connect directly after a verified phone number is provided.",body:<div className="contact-grid"><div><span>Phone / WhatsApp</span><p>{clinic.phoneDisplay}</p></div><div><span>Email</span><p>{clinic.email}</p></div><div><span>Address</span><p>{clinic.address}</p></div><div><span>Hours</span><p>{clinic.hours}</p></div><div className="map-placeholder"><span>Clinic location</span><strong>Gyanpur Dehat, beside the Primary School, Gyanpur, Bhadohi</strong><a href="https://www.google.com/maps/search/?api=1&query=Sampurna+Clinic+Gyanpur+Dehat+Bhadohi" target="_blank" rel="noopener noreferrer">Open in Google Maps →</a></div><Link className="button" href="/appointment">Book Appointment</Link></div>},
"privacy-policy":{eyebrow:"Privacy",title:"Your enquiry information should remain private.",intro:"How appointment details should be handled.",body:<div className="legal"><h2>Information collected</h2><p>The form requests contact details, preferred service, date and time. Reports, diagnosis or sensitive medical details na likhein.</p><h2>Purpose</h2><p>Information should be used only to respond to the enquiry and arrange the appointment.</p></div>},
terms:{eyebrow:"Website terms",title:"Important information about this website.",intro:"Please read before using the appointment form.",body:<div className="legal"><h2>Not medical advice</h2><p>Website content is general information and does not replace consultation, diagnosis or treatment.</p><h2>Emergencies</h2><p>This website is not monitored for emergencies. Contact the nearest hospital or local emergency service for urgent help.</p></div>}
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=pages[slug];return p?{title:`${p.title} | ${clinic.name}`,description:p.intro}:{}}
export default async function ContentPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const page=pages[slug];if(!page)notFound();return <><Header/><main><PageHero eyebrow={page.eyebrow} title={page.title} intro={page.intro}/><section className="content-section">{page.body}</section>{!["privacy-policy","terms","contact"].includes(slug)&&<CTA/>}</main><Footer/></>}





