import {notFound} from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import {CTA,Footer,Header,PageHero} from "../components";
import {clinic,doctors,faqs} from "../data";
const pages:Record<string,{eyebrow:string,title:string,intro:string,body:React.ReactNode}>={
about:{eyebrow:"About the clinic",title:"Women’s healthcare with privacy, clarity and respect.",intro:"A consultation experience designed to help patients feel heard, informed and comfortable asking questions.",body:<div className="prose-grid"><div><h2>Care begins with listening.</h2><p>Every health concern deserves context. The clinic approach is to understand your symptoms and history, explain the possible next steps and support informed decisions without promising outcomes.</p></div><div className="principles"><article><span>01</span><h3>Private</h3><p>A respectful setting for personal health conversations.</p></article><article><span>02</span><h3>Clear</h3><p>Medical information explained in understandable language.</p></article><article><span>03</span><h3>Considered</h3><p>Recommendations based on individual clinical assessment.</p></article></div></div>},
doctors:{eyebrow:"Doctor profile",title:"Meet your gynecologist.",intro:"The final approved doctor profile will appear here after verified details and photography are supplied.",body:<div className="doctor-showcase"><div className="doctor-photo"><Image src="/gynecologist-hero.png" alt="Generic gynecologist profile placeholder" fill sizes="(max-width:800px) 100vw,45vw"/></div><div><span>Verified profile pending</span><h2>{doctors[0].name}</h2><p>{doctors[0].role}. We will add the doctor’s approved photograph, qualifications, registration, experience and consultation timings after you share them.</p><Link className="button" href={`/doctors/${doctors[0].slug}`}>View Profile</Link></div></div>},
gallery:{eyebrow:"Clinic environment",title:"A calm setting for private consultations.",intro:"Approved photographs of reception, consultation room and clinic exterior will replace these current design visuals.",body:<div className="real-gallery"><div><Image src="/gynecologist-hero.png" alt="Generic modern gynecology consultation room" fill sizes="100vw"/></div><div className="gallery-placeholder">Approved clinic photography<br/>to be added</div></div>},
testimonials:{eyebrow:"Patient experiences",title:"Real feedback only.",intro:"Testimonials and ratings will be published only from a verifiable source and with appropriate consent.",body:<div className="empty-state"><h2>Verified reviews pending.</h2><p>No fabricated ratings, quotes or patient counts are used. Share approved Google Business Profile reviews or written testimonials after the website design is complete.</p></div>},
faq:{eyebrow:"Frequently asked questions",title:"Helpful information before your visit.",intro:"Clear answers about appointments, privacy and what to bring.",body:<div className="faq-list">{faqs.map((f,i)=><details key={f.q} open={i===0}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div>},
blog:{eyebrow:"Women’s health journal",title:"Reviewed information, written responsibly.",intro:"Educational content will be added only with an identified author, review date and reliable sources.",body:<div className="empty-state"><h2>Clinical articles are awaiting review.</h2><p>Website information must not replace diagnosis, treatment or individual advice from a qualified healthcare professional.</p></div>},
contact:{eyebrow:"Contact the clinic",title:"Your consultation can start with a simple request.",intro:"Replace the marked phone, email, address and timing placeholders with verified clinic information.",body:<div className="contact-grid"><div><span>Phone</span><a href={`tel:${clinic.phone}`}>{clinic.phoneDisplay}</a></div><div><span>Email</span><a href={`mailto:${clinic.email}`}>{clinic.email}</a></div><div><span>Address</span><p>{clinic.address}</p></div><div><span>Hours</span><p>{clinic.hours}</p></div><div className="map-placeholder">Verified Google Maps location<br/>will appear here</div></div>},
"privacy-policy":{eyebrow:"Privacy",title:"Your enquiry information should remain private.",intro:"How contact and appointment details should be handled.",body:<div className="legal"><h2>Information collected</h2><p>The form requests contact details, preferred service, date and time. Do not include reports, diagnoses or sensitive medical details.</p><h2>Purpose</h2><p>Information should be used only to respond to your enquiry and arrange the appointment. Final policy terms require legal review for the clinic’s jurisdiction.</p></div>},
terms:{eyebrow:"Website terms",title:"Important information about this website.",intro:"Please read these points before using the appointment form.",body:<div className="legal"><h2>Not medical advice</h2><p>Website content is general information and cannot replace consultation, diagnosis or treatment.</p><h2>Emergencies</h2><p>This website is not monitored for emergencies. Contact local emergency services for urgent medical help.</p></div>}
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=pages[slug];return p?{title:`${p.title} | ${clinic.name}`,description:p.intro}:{}}
export default async function ContentPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const page=pages[slug];if(!page)notFound();return <><Header/><main><PageHero eyebrow={page.eyebrow} title={page.title} intro={page.intro}/><section className="content-section">{page.body}</section>{!["privacy-policy","terms","contact"].includes(slug)&&<CTA/>}</main><Footer/></>}
