import {notFound} from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import {CTA,Footer,Header,PageHero} from "../components";
import {clinic,faqs} from "../data";

const pages:Record<string,{eyebrow:string,title:string,intro:string,body:React.ReactNode}>={
about:{eyebrow:"Hamari Clinic",title:"Gaon ke parivaar ke paas, bachchon ki pyaar bhari care.",intro:"Bade letters, simple baat aur bina uljhan ke doctor appointment.",body:<div className="prose-grid"><div><h2>Clinic ka seedha vaada</h2><p>Bachche ko pyaar se samajhna, maa-baap ke sawal dhyaan se sunna aur agla kadam aasaan shabdon mein batana.</p></div><div className="principles"><article><span>01</span><h3>Pehle sunein</h3><p>Aap apni baat poori tarah bata sakte hain.</p></article><article><span>02</span><h3>Saaf samjhayen</h3><p>Mushkil baat bhi simple shabdon mein.</p></article><article><span>03</span><h3>Agla kadam</h3><p>Ghar jaate waqt aapko pata ho ki kya karna hai.</p></article></div></div>},
doctors:{eyebrow:"Bachchon ke Doctor",title:"Pyaar se baat. Verified jankari.",intro:"Doctor ka verified naam, degree aur registration clinic se milte hi yahan dikhayenge.",body:<div className="doctor-showcase"><div className="doctor-photo"><Image src="/baby-doctor.png" alt="Friendly child doctor speaking with a mother and baby" fill sizes="(max-width:800px) 100vw, 45vw"/></div><div><span>Doctor profile jaldi aayegi</span><h2>Hum nakli qualification nahi likhte.</h2><p>Doctor ki asli details milne tak aap appointment request kar sakte hain. Clinic team aapko phone karke batayegi.</p><Link className="button" href="/appointment">Appointment Book Karein</Link></div></div>},
gallery:{eyebrow:"Clinic Photos",title:"Hamari saaf aur simple village clinic.",intro:"Yeh visual sample hain. Launch se pehle clinic ki asli approved photos lagengi.",body:<div className="real-gallery"><div><Image src="/village-clinic.png" alt="Blue and white child clinic in a village" fill sizes="100vw"/></div><div><Image src="/baby-doctor.png" alt="Baby consultation in a child-friendly clinic" fill sizes="(max-width:800px) 100vw, 45vw"/></div></div>},
testimonials:{eyebrow:"Parivaar ki Baat",title:"Sirf asli feedback.",intro:"Clinic se verified aur permission mila feedback hi yahan dikhaya jayega.",body:<div className="empty-state"><h2>Feedback jaldi aayega.</h2><p>Hum nakli rating, patient count ya quotes publish nahi karte.</p></div>},
faq:{eyebrow:"Sawal-Jawab",title:"Clinic aane se pehle seedhe jawab.",intro:"Appointment, timing aur visit se jude aasaan sawal.",body:<div className="faq-list">{faqs.map((f,i)=><details key={f.q} open={i===0}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div>},
blog:{eyebrow:"Bachchon ki Sehat",title:"Simple health jankari.",intro:"Doctor se reviewed articles yahan milenge. Website ki jankari doctor consultation ki jagah nahi leti.",body:<div className="empty-state"><h2>Articles review mein hain.</h2><p>Hum bina medical review ke generic health advice publish nahi karte.</p></div>},
contact:{eyebrow:"Sampark",title:"Clinic se baat karna bilkul aasaan.",intro:"Phone karein, address dekhein ya appointment form bhariye. Final launch se pehle verified phone, timing aur address add karein.",body:<div className="contact-grid"><div><span>Phone</span><a href={`tel:${clinic.phone}`}>{clinic.phoneDisplay}</a></div><div><span>Email</span><a href={`mailto:${clinic.email}`}>{clinic.email}</a></div><div><span>Pata</span><p>{clinic.address}</p></div><div><span>Samay</span><p>{clinic.hours}</p></div><div className="map-placeholder">Google Map yahan aayega<br/>jab verified location milegi</div></div>},
"privacy-policy":{eyebrow:"Privacy",title:"Aapki jankari surakshit rahe.",intro:"Form mein sirf appointment ke liye zaroori baat poochi jaati hai.",body:<div className="legal"><h2>Hum kya lete hain</h2><p>Naam, phone, email aur pasand ka appointment time. Form mein reports ya private medical details na bhejein.</p><h2>Kyun lete hain</h2><p>Sirf appointment ke liye aapse sampark karne ke liye. Final policy clinic ke kanooni review ke baad update hogi.</p></div>},
terms:{eyebrow:"Zaroori Baat",title:"Website ka sahi istemaal.",intro:"Yeh website appointment aur general jankari ke liye hai.",body:<div className="legal"><h2>Emergency nahi</h2><p>Emergency mein website form ka use na karein. Apni local emergency service ya najdeeki hospital se turant sampark karein.</p><h2>Medical advice nahi</h2><p>Website ki jankari doctor ki jaanch, diagnosis ya treatment ka badal nahi hai.</p></div>}
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=pages[slug];return p?{title:`${p.title} | ${clinic.name}`,description:p.intro}:{}}
export default async function ContentPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const page=pages[slug];if(!page)notFound();return <><Header/><main><PageHero eyebrow={page.eyebrow} title={page.title} intro={page.intro}/><section className="content-section">{page.body}</section>{!["privacy-policy","terms","contact"].includes(slug)&&<CTA/>}</main><Footer/></>}

