import {notFound} from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import {CTA,Footer,Header} from "../../components";
import {clinic,doctors,services} from "../../data";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const doctor=doctors.find(d=>d.slug===slug);return doctor?{title:`${doctor.name} | ${clinic.name}`,description:`Professional profile of ${doctor.name} at ${clinic.name}.`,openGraph:{images:[]},twitter:{images:[]}}:{}}
export default async function DoctorProfile({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const doctor=doctors.find(d=>d.slug===slug);if(!doctor)notFound();return <><Header/><main className="doctor-editorial">
<section className="doctor-profile-hero"><div className="doctor-profile-copy"><p className="eyebrow">Sampurna Clinic • Gyanpur, Bhadohi</p><h1>Clear guidance for every stage of women’s health.</h1><p>Meet {doctor.name} for private consultations related to women’s health, maternity and infertility concerns.</p><div><Link className="button" href="/appointment">Book an Appointment <span>→</span></Link><Link href="/contact">View Clinic Details</Link></div><ul><li>Private consultations</li><li>Individual assessment</li><li>Clearly explained next steps</li></ul></div><div className="doctor-profile-art"><Image src="/doctor-care-hero-v2.png" alt="Representative mother, baby and women’s health consultation collage" fill priority sizes="(max-width:900px) 100vw,55vw"/></div></section>
<section className="doctor-identity"><Image src="/sampurna-clinic-logo.png" alt="Sampurna Clinic logo" width={130} height={130}/><div><p className="eyebrow">Doctor profile</p><h2>{doctor.name}</h2><p>{doctor.role}</p></div><dl><div><dt>Qualification</dt><dd>{doctor.qualification}</dd></div><div><dt>Location</dt><dd>Gyanpur, Bhadohi</dd></div><div><dt>Consultation</dt><dd>{doctor.availability}</dd></div></dl></section>
<section className="doctor-help"><div className="doctor-help-cards"><article><span>01</span><h3>Women’s Health</h3><p>Consultation for menstrual, hormonal and general gynecology concerns.</p></article><article><span>02</span><h3>Pregnancy Care</h3><p>Stage-appropriate guidance and follow-up planning during pregnancy.</p></article><article><span>03</span><h3>Fertility Questions</h3><p>A respectful first discussion about evaluation and possible next steps.</p></article><article><span>04</span><h3>Preventive Guidance</h3><p>Check-up and screening discussions based on age, history and clinical need.</p></article></div><div className="doctor-help-copy"><p className="eyebrow">How the doctor can help</p><h2>Care that starts with listening.</h2><p>The consultation begins with your concerns and relevant history. The doctor may recommend advice, examination, investigation, treatment or referral after individual assessment.</p><Link className="button" href="/blog">Read Women’s Health Guide →</Link></div></section>
<section className="doctor-services"><header><p className="eyebrow">Clinical support</p><h2>Consultation areas at Sampurna Clinic</h2><p>These pages explain the purpose of each consultation without promising a specific diagnosis or outcome.</p></header><div>{services.map((service,index)=><Link href={`/services/${service.slug}`} key={service.slug}><span>{String(index+1).padStart(2,"0")}</span><b>{service.title}</b><i>→</i></Link>)}</div></section>
<section className="doctor-journey"><div><Image src="/clinic-consultation-v2.png" alt="Representative private consultation" fill sizes="(max-width:900px) 100vw,48vw"/></div><article><p className="eyebrow">Your consultation journey</p><h2>Simple, private and clearly explained.</h2><ol><li><span>1</span><div><b>Request</b><p>Choose a service, preferred date and time.</p></div></li><li><span>2</span><div><b>Confirm</b><p>The clinic confirms appointment availability.</p></div></li><li><span>3</span><div><b>Consult</b><p>Discuss your concern and relevant history privately.</p></div></li><li><span>4</span><div><b>Plan</b><p>Receive next steps based on clinical assessment.</p></div></li></ol></article></section>
<section className="doctor-reviews"><div><p className="eyebrow">Patient feedback</p><h2>Trust must be genuine.</h2><p>No fabricated rating, testimonial, patient count or “best doctor” claim is displayed. Verified Google reviews or consented patient feedback can be published after the clinic supplies the source.</p></div><aside><span>Rating</span><strong>Awaiting verified reviews</strong><Link href="/contact">Share a verified review source →</Link></aside></section>
<CTA/></main><Footer/></>}


