import {notFound} from "next/navigation";
import Link from "next/link";
import {CTA,Footer,Header,PageHero} from "../../components";
import {clinic,doctors} from "../../data";

export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const doctor=doctors.find(d=>d.slug===slug);return doctor?{title:`${doctor.name} | ${clinic.name}`,description:`${doctor.role}. Verified profile details will be added before launch.`,openGraph:{images:[]},twitter:{images:[]}}:{}}
export default async function DoctorProfile({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const doctor=doctors.find(d=>d.slug===slug);if(!doctor)notFound();return <><Header/><main><PageHero eyebrow="Doctor Profile / Doctor ki jankari" title={doctor.name} intro="Is page par sirf clinic se mili hui verified doctor details publish hongi."/><section className="content-section profile-layout"><aside className="profile-card" style={{background:doctor.color}}><div className="doctor-avatar">{doctor.initials}</div><h2>{doctor.name}</h2><p>{doctor.role}</p><div className="rating-pending">☆ Rating: verified reviews milne ke baad</div><Link className="button" href="/appointment">Book Appointment / Appointment Book Karein</Link></aside><article className="profile-details"><p className="section-label">Doctor ki jankari</p><h2>Profile Details / Puri jankari</h2><dl><div><dt>Qualification</dt><dd>{doctor.qualification}</dd></div><div><dt>Experience</dt><dd>{doctor.experience}</dd></div><div><dt>Registration</dt><dd>{doctor.registration}</dd></div><div><dt>Clinic Timing</dt><dd>{doctor.availability}</dd></div></dl><div className="verify-note"><b>Verified information only</b><p>Doctor ka asli naam, photo, degree, specialty, experience aur registration number milte hi yahan update hoga. Fake rating ya medical claim publish nahi kiya jayega.</p></div><h2>When to visit? / Doctor se kab milein?</h2><p>Baby ki tabiyat, growth, vaccination ya nutrition se jude sawal ke liye appointment request karein. Emergency mein website form ka use na karein.</p></article></section><CTA/></main><Footer/></>}


